// I get this data from api:
// https://api.soccersapi.com/v2.2/countries/?user=juandacorreo&token=7283c63298d92adfccfffb26bead8f7c&t=list&page=1
// https://api.soccersapi.com/v2.2/countries/?user=juandacorreo&token=7283c63298d92adfccfffb26bead8f7c&t=list&page=1

// As this data is not subject to change and its always needed before  hand I process it on build time:

//  remove first values (continents, World, simulated league as they are not countries)
// and order and remove extra properties with  something like
// const  filteredCountries = countries.map(({id, name}) => ({id,  name})).sort((a,b) =>a.name-b.name)

export const countries: { id: number; name: string }[] = [
  { id: 8, name: 'Albania' },
  { id: 9, name: 'Algeria' },
  { id: 10, name: 'Andorra' },
  { id: 11, name: 'Angola' },
  { id: 12, name: 'Argentina' },
  { id: 13, name: 'Armenia' },
  { id: 14, name: 'Australia' },
  { id: 15, name: 'Austria' },
  { id: 17, name: 'Azerbaijan' },
  { id: 18, name: 'Bahrain' },
  { id: 19, name: 'Bangladesh' },
  { id: 20, name: 'Belarus' },
  { id: 21, name: 'Belgium' },
  { id: 22, name: 'Bolivia' },
  { id: 23, name: 'Bosnia & Herzegovina' },
  { id: 24, name: 'Botswana' },
  { id: 25, name: 'Brazil' },
  { id: 26, name: 'Bulgaria' },
  { id: 134, name: 'Cambodia' },
  { id: 27, name: 'Cameroon' },
  { id: 28, name: 'Canada' },
  { id: 29, name: 'Chile' },
  { id: 30, name: 'China' },
  { id: 31, name: 'Colombia' },
  { id: 32, name: 'Congo' },
  { id: 33, name: 'Costa Rica' },
  { id: 34, name: 'Croatia' },
  { id: 35, name: 'Cyprus' },
  { id: 36, name: 'Czech Republic' },
  { id: 37, name: 'Denmark' },
  { id: 39, name: 'Ecuador' },
  { id: 40, name: 'Egypt' },
  { id: 41, name: 'El Salvador' },
  { id: 3, name: 'England' },
  { id: 43, name: 'Estonia' },
  { id: 142, name: 'Ethiopia' },
  { id: 44, name: 'Faroe Islands' },
  { id: 45, name: 'Finland' },
  { id: 7, name: 'France' },
  { id: 46, name: 'Georgia' },
  { id: 4, name: 'Germany' },
  { id: 48, name: 'Ghana' },
  { id: 49, name: 'Gibraltar' },
  { id: 50, name: 'Greece' },
  { id: 51, name: 'Guatemala' },
  { id: 52, name: 'Honduras' },
  { id: 53, name: 'Hong Kong' },
  { id: 54, name: 'Hungary' },
  { id: 55, name: 'Iceland' },
  { id: 56, name: 'India' },
  { id: 57, name: 'Indonesia' },
  { id: 59, name: 'Iran' },
  { id: 60, name: 'Ireland' },
  { id: 61, name: 'Israel' },
  { id: 6, name: 'Italy' },
  { id: 62, name: 'Ivory Coast' },
  { id: 63, name: 'Jamaica' },
  { id: 64, name: 'Japan' },
  { id: 65, name: 'Jordan' },
  { id: 66, name: 'Kazakhstan' },
  { id: 67, name: 'Kenya' },
  { id: 68, name: 'Kosovo' },
  { id: 69, name: 'Kuwait' },
  { id: 70, name: 'Latvia' },
  { id: 71, name: 'Lebanon' },
  { id: 131, name: 'Liechtenstein' },
  { id: 72, name: 'Lithuania' },
  { id: 73, name: 'Luxembourg' },
  { id: 74, name: 'Malaysia' },
  { id: 75, name: 'Malta' },
  { id: 76, name: 'Mexico' },
  { id: 77, name: 'Moldova' },
  { id: 78, name: 'Montenegro' },
  { id: 79, name: 'Morocco' },
  { id: 80, name: 'Myanmar' },
  { id: 81, name: 'Netherlands' },
  { id: 82, name: 'New Zealand' },
  { id: 83, name: 'Nicaragua' },
  { id: 84, name: 'Nigeria' },
  { id: 86, name: 'North Macedonia' },
  { id: 85, name: 'Northern Ireland' },
  { id: 87, name: 'Norway' },
  { id: 88, name: 'Oman' },
  { id: 89, name: 'Pakistan' },
  { id: 90, name: 'Palestine' },
  { id: 91, name: 'Panama' },
  { id: 92, name: 'Paraguay' },
  { id: 93, name: 'Peru' },
  { id: 94, name: 'Philippines' },
  { id: 95, name: 'Poland' },
  { id: 96, name: 'Portugal' },
  { id: 97, name: 'Qatar' },
  { id: 98, name: 'Republic of Korea' },
  { id: 99, name: 'Romania' },
  { id: 100, name: 'Russia' },
  { id: 101, name: 'Rwanda' },
  { id: 102, name: 'San Marino' },
  { id: 103, name: 'Saudi Arabia' },
  { id: 104, name: 'Scotland' },
  { id: 105, name: 'Senegal' },
  { id: 106, name: 'Serbia' },
  { id: 107, name: 'Singapore' },
  { id: 108, name: 'Slovakia' },
  { id: 109, name: 'Slovenia' },
  { id: 110, name: 'South Africa' },
  { id: 5, name: 'Spain' },
  { id: 112, name: 'Sweden' },
  { id: 114, name: 'Switzerland' },
  { id: 115, name: 'Tanzania' },
  { id: 116, name: 'Thailand' },
  { id: 132, name: 'Trinidad and Tobago' },
  { id: 117, name: 'Tunisia' },
  { id: 118, name: 'Turkey' },
  { id: 120, name: 'Uganda' },
  { id: 121, name: 'Ukraine' },
  { id: 122, name: 'United Arab Emirates' },
  { id: 123, name: 'Uruguay' },
  { id: 124, name: 'USA' },
  { id: 125, name: 'Uzbekistan' },
  { id: 126, name: 'Venezuela' },
  { id: 127, name: 'Vietnam' },
  { id: 128, name: 'Wales' },
  { id: 129, name: 'Zambia' },
  { id: 130, name: 'Zimbabwe' },
]
