export const TEAM_URL = '/my-team'
export const TEAMS_LIST_URL = '/teams'
export const HOME_URL = '/'
export const NOT_FOUND_URL = '*'
export const API_TOKEN = '7283c63298d92adfccfffb26bead8f7c'
export const API_USER = 'juandacorreo'
